name: "service-a"

deployment:
  replicaCount: 1

  image:
    image: offerfit-service-a
    tag: f36dd48

  env:
    - name: "APP_PORT"
      value: 8011
    - name: "APP_VERSION"
      value: f36dd48

service:
  port: 8011

ingress:
  enabled: true
