controller:
  nodeSelector:
    tier: backstage
  name: controller
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  admissionWebhooks:
    enabled: false
  ingressClassResource:
    name: nginx
    default: true
  hostPort:
    enabled: true
  replicaCount: 1