namespace: default
environment: default

deployment:
  replicaCount: 1

  image:
    repository: registry-1.docker.io/victoramsantos
    image: blank
    tag: dev

  application:
    healthPath: /health

  defaultEnvs: {}

  envFromFields:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  host: offerfit.local