name: "service-b"

deployment:
  replicaCount: 1

  image:
    image: offerfit-service-b
    tag: test

  env:
    - name: "APP_PORT"
      value: 8012
    - name: "SERVICE_A_PORT"
      value: 8011

service:
  port: 8012
