apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-{{ include "app.name" . }}-service
  namespace: {{ .Values.namespace }}
  labels: {{ include "app.labels" . | nindent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "app.labels" . | nindent 8}}
