global:
  nodeSelector:
    tier: backstage

server:
  extraArgs:
    - --insecure

  ingress:
    enabled: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "300m"
    limits:
      memory: "300Mi"
      cpu: "300m"

redis:
  enabled: true
  architecture: standalone

redis-ha:
  enabled: false

controller:
  metrics:
    enabled: false

repoServer:
  metrics:
    enabled: false

applicationSet:
  enabled: false

notifications:
  enabled: false

dex:
  enabled: false

configs:
  cm:
    timeout.reconciliation: 20s
    timeout.hard.reconciliation: 60s
