name: Python CI
on:
  push:
    paths:
      - 'app/service-a/**'
      - 'app/service-b/**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        APP_NAME: [ "service-a", "service-b" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r ./app/${{ matrix.APP_NAME }}/requirements.txt

      - name: Run tests for ${{ matrix.APP_NAME }}
        run: python -m unittest discover -s ./app/${{ matrix.APP_NAME }}/src -p "test_*.py"
