name: Tag Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest

      - name: Tag and push versioned image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:$VERSION
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:$VERSION