name: Tag Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-process:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        APP_NAME: [ "service-a", "service-b" ]
    steps:
      - name: Checkout release code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building ${{ matrix.APP_NAME }}
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.VENDOR_IMG_PREFIX }}-${{matrix.APP_NAME}}:${TAG} ./app/${{matrix.APP_NAME}}/.

      - name: Push Docker image
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.VENDOR_IMG_PREFIX }}-${{matrix.APP_NAME}}:${TAG}

      - name: Update ${{ matrix.APP_NAME }}/deployment-config/production/values.yaml with new tag
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          cd app/${{ matrix.APP_NAME }}/deploy-config/production
          
          sed -i "s/tag:.*/tag: ${TAG}/" values.yaml
          sed -i '/name: "APP_VERSION"/ { n; s/value:.*/value: '"${TAG}"'/; }' values.yaml
          
          echo "Updated ${{ matrix.APP_NAME }}/deploy-config/production/values.yaml content:"
          cat values.yaml

      - name: Commit and push changes
        env:
          TAG: ${{ github.event.release.tag_name }}
          BRANCH: main
          BOT_NAME: github-actions[bot]
        run: |
          git config user.name "${BOT_NAME}"
          git config user.email "${BOT_NAME}@users.noreply.github.com"          
          
          git pull origin $BRANCH
          git checkout $BRANCH
          git add app/${{ matrix.APP_NAME }}/deploy-config/production/values.yaml
          git commit -m "ci: update ${{ matrix.APP_NAME }} image tag to ${TAG}"
          git push origin $BRANCH --force